apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ashok-dev
  name: namespace-admin
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "create", "delete", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete", "update"]
